"""Human-readable current-state projection for one Project Outcome.

The packet is deliberately one-way: it reads the root-shared Outcome store and
Git facts and materializes ``docs/outcomes/<KEY>/00-status.md``.  It never
parses that markdown back into state, so the document cannot become a competing
authority.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any, Mapping, Optional

from hermes_cli import outcomes_db as odb


def _git_capture(repo: Path, *args: str) -> Optional[str]:
    """Return stdout for a successful Git command, preserving empty output.

    Empty stdout is meaningful for commands such as ``git status --porcelain``
    (a clean checkout).  Callers that want an absent/empty value collapsed to
    ``None`` can use :func:`_git` instead.
    """
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), *args],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
            shell=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout.strip()


def _git(repo: Path, *args: str) -> Optional[str]:
    value = _git_capture(repo, *args)
    return value or None


def git_projection(repo: Path) -> dict[str, Any]:
    repo = repo.expanduser().resolve(strict=False)
    head = _git(repo, "rev-parse", "HEAD")
    branch = _git(repo, "branch", "--show-current")
    origin = _git(repo, "config", "--get", "remote.origin.url")
    origin_main = _git(repo, "rev-parse", "origin/main")
    # Outcome packets are generated projection artifacts, not source changes.
    # Ignore their own directory so materializing several Outcomes in one clean
    # checkout does not make the second packet claim the source checkout is dirty.
    status = _git_capture(
        repo,
        "status",
        "--porcelain",
        "--",
        ".",
        ":(exclude)docs/outcomes/**",
    )
    return {
        "repo": str(repo),
        "head": head,
        "branch": branch,
        "origin": origin,
        "origin_main": origin_main,
        "clean": status == "" if status is not None else None,
    }


def _as_lines(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, Mapping):
        return [f"{key}: {json.dumps(val, ensure_ascii=False, sort_keys=True)}" for key, val in value.items()]
    if isinstance(value, (list, tuple, set)):
        result: list[str] = []
        for item in value:
            if isinstance(item, str):
                result.append(item)
            else:
                result.append(json.dumps(item, ensure_ascii=False, sort_keys=True))
        return result
    return [json.dumps(value, ensure_ascii=False, sort_keys=True)]


def render_status(
    *,
    project_name: str,
    outcome: odb.Outcome,
    snapshot: Mapping[str, Any],
    repo_state: Optional[Mapping[str, Any]] = None,
) -> str:
    leases = [
        lease
        for lease in snapshot.get("active_mutation_leases", [])
        if lease.get("outcome_id") == outcome.id
    ]
    lanes = [
        lane
        for lane in snapshot.get("conversation_lanes", [])
        if lane.get("outcome_id") in {None, outcome.id}
    ]
    acceptance = _as_lines(outcome.frozen_acceptance)

    lines = [
        f"# {outcome.outcome_key}",
        "",
        "> Generated current-state projection. Do not edit this file as an authority; ",
        "> Project/Outcome state, Git, runtime, source systems, and frozen contracts remain authoritative.",
        "",
        f"- Project: `{project_name}` (`{outcome.project_id}`)",
        f"- Outcome ID: `{outcome.id}`",
        f"- State: `{outcome.state}`",
        f"- Visible owner: `{outcome.visible_owner or 'unassigned'}`",
        f"- Current base: `{outcome.current_base_ref or 'not set'}`",
        f"- Current candidate: `{outcome.current_candidate_ref or 'none'}`",
        f"- Current live release: `{outcome.current_live_ref or 'none'}`",
        f"- Next action: {outcome.next_action or 'none recorded'}",
        "",
        "## Active mutation ownership",
        "",
    ]
    if leases:
        for lease in leases:
            scope = ", ".join(f"`{item}`" for item in lease.get("path_scope", [])) or "none"
            lines.extend(
                [
                    f"- Execution: `{lease.get('owner_execution_id')}`",
                    f"  - Repository: `{lease.get('repository')}`",
                    f"  - Base: `{lease.get('base_ref') or 'not set'}`",
                    f"  - Scope: {scope}",
                    f"  - Lease expires: `{lease.get('expires_at') or 'not set'}`",
                ]
            )
    else:
        lines.append("- No active mutating execution.")

    lines.extend(["", "## Conversation lanes", ""])
    if lanes:
        for lane in lanes:
            target = f"{lane.get('platform')}:{lane.get('chat_id')}"
            if lane.get("thread_id"):
                target += f":{lane.get('thread_id')}"
            binding = "project control" if not lane.get("outcome_id") else "this outcome"
            lines.append(
                f"- `{lane.get('label') or target}` — `{target}` ({lane.get('lane_kind')}, {binding})"
            )
    else:
        lines.append("- No conversation lane bound.")

    lines.extend(["", "## Frozen acceptance", ""])
    if acceptance:
        lines.extend(f"- {item}" for item in acceptance)
    else:
        lines.append("- No frozen acceptance recorded in Outcome state.")

    lines.extend(["", "## Git projection", ""])
    if repo_state:
        lines.extend(
            [
                f"- Repository: `{repo_state.get('repo')}`",
                f"- Materialization checkout: `{repo_state.get('branch') or 'detached'}`",
                f"- HEAD: `{repo_state.get('head') or 'unknown'}`",
                f"- origin/main: `{repo_state.get('origin_main') or 'unknown'}`",
                f"- Source checkout clean (excluding generated `docs/outcomes/**`): `{repo_state.get('clean')}`",
            ]
        )
    else:
        lines.append("- Repository projection not requested.")
    lines.append("")
    return "\n".join(lines)


def materialize_status(
    *,
    project_id: str,
    project_name: str,
    outcome_id: str,
    repo: Path,
) -> Path:
    repo = repo.expanduser().resolve(strict=False)
    with odb.connect_closing() as conn:
        outcome = odb.get_outcome(conn, outcome_id, project_id=project_id)
        if outcome is None:
            raise ValueError("outcome does not resolve inside project")
        snapshot = odb.project_snapshot(conn, project_id)
    target_dir = repo / "docs" / "outcomes" / outcome.outcome_key
    target_dir.mkdir(parents=True, exist_ok=True)
    (target_dir / "receipts").mkdir(parents=True, exist_ok=True)
    target = target_dir / "00-status.md"
    target.write_text(
        render_status(
            project_name=project_name,
            outcome=outcome,
            snapshot=snapshot,
            repo_state=git_projection(repo),
        ),
        encoding="utf-8",
    )
    return target
